#include "dpp/convert/iostream.h"
#include "dpp/string_utils.h"

#include <cctype>
#include <map>
#include <regex>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace dpp::convert {
namespace {

bool is_string_literal(const std::string &value) {
  return value.size() >= 2 && value.front() == '"' && value.back() == '"';
}

bool is_size_expression(const std::string &value) {
  if (value.find("dpp_vector_at(") != std::string::npos ||
      value.find("dpp_vector_const_at(") != std::string::npos) {
    return false;
  }
  if (value.find("== 0") != std::string::npos || value.find("!= 0") != std::string::npos) {
    return false;
  }
  return value.find(".size()") != std::string::npos ||
         value.find("dpp_string_size(") != std::string::npos ||
         value.find("dpp_vector_size(") != std::string::npos ||
         value.find("dpp_map_size(") != std::string::npos ||
         value.find("dpp_unordered_map_size(") != std::string::npos;
}

bool is_string_char_subscript(const std::string &value) {
  // dpp_string_c_str(...)[idx] — single char element, use %c
  const std::size_t pos = value.find("dpp_string_c_str(");
  if (pos == std::string::npos) return false;
  const std::size_t close = value.find(')', pos);
  return close != std::string::npos && close + 1 < value.size() && value[close + 1] == '[';
}

bool is_c_string_expression(const std::string &value) {
  if (is_string_char_subscript(value)) return false;
  // dpp_string_c_str is only a string at the outermost level; when nested inside
  // another call (e.g. foo(dpp_string_c_str(&x))), the expression is NOT a string.
  const std::string tp = trim(value);
  if (tp.rfind("dpp_string_c_str(", 0) == 0)
    return true;
  // dpp_map_key_at is always inside a deref cast generated by the map pass, so
  // use a "contains" check: (*(const char * *)dpp_map_key_at(&m, i))
  if (value.find("dpp_map_key_at(") != std::string::npos ||
      value.find("->name") != std::string::npos)
    return true;
  // ternary returning string literals: (cond ? "s1" : "s2") or (cond ? "s" : var)
  const auto qpos = value.find('?');
  if (qpos != std::string::npos) {
    for (std::size_t i = qpos + 1; i < value.size(); ++i) {
      if (value[i] == '"') return true;
      if (!std::isspace(static_cast<unsigned char>(value[i]))) break;
    }
  }
  return false;
}

bool is_double_expression(const std::string &value) {
  if (value.find("double *") != std::string::npos ||
      value.find("dpp_min_element_double(") != std::string::npos ||
      value.find("dpp_max_element_double(") != std::string::npos ||
      value.find("dpp_accumulate_double(") != std::string::npos) {
    return true;
  }
  for (std::size_t i = 0; i < value.size(); ++i) {
    if (value[i] != '.') continue;
    const bool has_digit_before = i > 0 && std::isdigit(static_cast<unsigned char>(value[i - 1]));
    const bool has_digit_after =
        i + 1 < value.size() && std::isdigit(static_cast<unsigned char>(value[i + 1]));
    if (has_digit_before || has_digit_after) return true;
  }
  return false;
}

bool is_char_literal(const std::string &value) {
  return value.size() >= 3 && value.front() == '\'' && value.back() == '\'';
}

bool is_unsigned_expression(const std::string &value) {
  return value.find("unsigned") != std::string::npos ||
         starts_with(value, "(unsigned");
}

bool is_long_expression(const std::string &value) {
  if (value.size() < 2) return false;
  const char last = value.back();
  if ((last != 'L' && last != 'l') || !std::isdigit(static_cast<unsigned char>(value[value.size() - 2])))
    return false;
  return true;
}

// Split a cout chain on top-level << operators, respecting string/char literals
// and parenthesised sub-expressions so that "a << b" or (x << 1) are not split.
std::vector<std::string> split_cout_chain(const std::string &chain) {
  std::vector<std::string> parts;
  std::size_t start = 0;
  bool in_string = false;
  bool in_char = false;
  int paren_depth = 0;

  for (std::size_t i = 0; i < chain.size(); ++i) {
    const char c = chain[i];
    if (in_string) {
      if (c == '\\') { ++i; }       // skip escape sequence
      else if (c == '"') { in_string = false; }
      continue;
    }
    if (in_char) {
      if (c == '\\') { ++i; }
      else if (c == '\'') { in_char = false; }
      continue;
    }
    if (c == '"') { in_string = true; continue; }
    if (c == '\'') { in_char = true; continue; }
    if (c == '(') { ++paren_depth; continue; }
    if (c == ')') { if (paren_depth > 0) --paren_depth; continue; }

    if (paren_depth == 0 && c == '<' && i + 1 < chain.size() && chain[i + 1] == '<') {
      parts.push_back(trim(chain.substr(start, i - start)));
      start = i + 2;
      ++i; // skip second '<'
    }
  }
  const std::string tail = trim(chain.substr(start));
  if (!tail.empty()) {
    parts.push_back(tail);
  }
  return parts;
}

std::string format_spec_for_type(const std::string &ctype) {
  if (ctype == "double" || ctype == "float") return "%g";
  if (ctype == "char") return "%c";
  if (ctype == "long") return "%ld";
  if (ctype == "unsigned int" || ctype == "unsigned") return "%u";
  if (ctype == "const char *" || ctype == "const char*") return "%s";
  if (ctype == "size_t" || ctype == "std::size_t") return "%zu";
  return "";
}

std::string lower_cout_line(const std::string &line, bool &used_stdio,
                            const std::map<std::string, std::string> &var_types,
                            const std::set<std::string> &str_ret_fns = {},
                            const std::map<std::string, std::string> &fn_ret_types = {}) {
  const std::string orig_stripped = trim(line);
  const std::string indent = leading_indent(line);

  // Strip case/default label: "case N: std::cout << ...; break;"
  static const std::regex label_re(R"(^((?:case\s+[^:]+:|default\s*:)\s*))");
  std::string label_prefix;
  bool had_break = false;
  std::smatch lm;
  std::string stripped = orig_stripped;
  if (std::regex_search(orig_stripped, lm, label_re)) {
    label_prefix = lm[1].str();
    stripped = orig_stripped.substr(lm[0].length());
    static const std::regex break_re(R"(\s*break\s*;\s*$)");
    if (std::regex_search(stripped, break_re)) {
      had_break = true;
      stripped = std::regex_replace(stripped, break_re, "");
      stripped = trim(stripped);
    }
  }

  std::string chain;
  bool to_stderr = false;

  if (starts_with(stripped, "std::cout")) {
    chain = trim(stripped.substr(std::string("std::cout").size()));
  } else if (starts_with(stripped, "cout")) {
    chain = trim(stripped.substr(std::string("cout").size()));
  } else if (starts_with(stripped, "std::cerr")) {
    chain = trim(stripped.substr(std::string("std::cerr").size()));
    to_stderr = true;
  } else if (starts_with(stripped, "cerr")) {
    chain = trim(stripped.substr(std::string("cerr").size()));
    to_stderr = true;
  } else {
    // Handle "if (cond) std::cout << ..." — single-line inline body form.
    // Find the stream keyword after a control-flow prefix.
    std::size_t stream_pos = std::string::npos;
    for (const char *kw : {"std::cout", "std::cerr"}) {
      const auto p = stripped.find(kw);
      if (p != std::string::npos && p > 0) {
        if (stream_pos == std::string::npos || p < stream_pos) {
          stream_pos = p;
        }
      }
    }
    if (stream_pos != std::string::npos) {
      const std::string ctrl_prefix = trim(stripped.substr(0, stream_pos));
      std::string cout_part = stripped.substr(stream_pos);
      if (!ctrl_prefix.empty()) {
        // Strip a trailing " }" from the cout_part if it's from an inline for/if body.
        std::string trailing_brace;
        std::string stripped_cout = trim(cout_part);
        if (!stripped_cout.empty() && stripped_cout.back() == '}') {
          // Peel off the closing brace (e.g. from "for (...) { cout << ...; }")
          stripped_cout.pop_back();
          stripped_cout = trim(stripped_cout);
          trailing_brace = " }";
        }
        const std::string inner_line = indent + "  " + stripped_cout;
        const std::string lowered_inner = lower_cout_line(inner_line, used_stdio, var_types, str_ret_fns);
        const std::string lowered_trimmed = trim(lowered_inner);
        return indent + label_prefix + ctrl_prefix + " " + lowered_trimmed + trailing_brace;
      }
    }
    return line;
  }

  if (!starts_with(chain, "<<") || chain.back() != ';') {
    return line;
  }

  used_stdio = true;
  chain = trim(chain.substr(2, chain.size() - 3));
  std::string format;
  std::vector<std::string> args;
  const std::vector<std::string> parts = split_cout_chain(chain);
  for (const std::string &part : parts) {
    if (part.empty()) {
      continue;
    }
    if (part == "std::endl" || part == "endl") {
      format += "\\n";
    } else if (is_string_literal(part)) {
      format += "%s";
      args.push_back(part);
    } else if (is_string_char_subscript(part)) {
      format += "%c";
      args.push_back(part);
    } else if (is_c_string_expression(part)) {
      format += "%s";
      if (part.find("->name") != std::string::npos &&
          part.find("dpp_string_c_str(") == std::string::npos) {
        args.push_back("dpp_string_c_str(&" + part + ")");
      } else {
        args.push_back(part);
      }
    } else if (is_size_expression(part)) {
      format += "%zu";
      args.push_back(part);
    } else if ([&]() -> bool {
        // If this is a call to a function with a known non-double return type, don't
        // let floating-point literals in the arguments drive the format spec.
        static const std::regex call_id_re(R"(^([A-Za-z_]\w*)\s*\()");
        std::smatch fcm;
        if (std::regex_search(part, fcm, call_id_re)) {
          const auto frit = fn_ret_types.find(fcm[1].str());
          if (frit != fn_ret_types.end() && frit->second != "double" && frit->second != "float")
            return false;
        }
        return is_double_expression(part);
      }()) {
      format += "%g";
      args.push_back(part);
    } else if (is_char_literal(part)) {
      format += "%c";
      args.push_back(part);
    } else if (is_long_expression(part)) {
      format += "%ld";
      args.push_back(part);
    } else if (is_unsigned_expression(part)) {
      format += "%u";
      args.push_back(part);
    } else {
      // Check if part (or any identifier in it) has a known type
      const std::string fs = [&]() -> std::string {
        const std::string tp = trim(part);
        // Exact match first
        const auto it = var_types.find(tp);
        if (it != var_types.end()) return format_spec_for_type(it->second);
        // Cast-dereference expressions: `(*(int *)expr)` — use the cast type.
        static const std::regex cast_deref_re(R"(^\(\s*\*\s*\(\s*(int|long|double|float|char|unsigned)\s*\*\s*\))");
        std::smatch cd_m;
        if (std::regex_search(tp, cd_m, cast_deref_re)) {
          return format_spec_for_type(cd_m[1].str().empty() ? "int" : cd_m[1].str());
        }
        // Member access: varname.value on a dpp_opt_T → use T's format spec.
        static const std::regex member_re(R"(^([A-Za-z_]\w*)\.value\s*$)");
        std::smatch mem_m;
        if (std::regex_match(tp, mem_m, member_re)) {
          const auto vit = var_types.find(mem_m[1].str());
          if (vit != var_types.end()) {
            const std::string vtype = vit->second;
            if (vtype.rfind("dpp_opt_", 0) == 0) {
              const std::string inner = vtype.substr(8); // strip "dpp_opt_"
              if (inner == "int" || inner == "long" || inner == "char" || inner == "dbl")
                return inner == "dbl" ? "%g" : (inner == "long" ? "%ld" : (inner == "char" ? "%c" : "%d"));
            }
          }
        }
        // Member access: varname.first / varname.second on a dpp_pair_T_U.
        static const std::regex pair_mem_re(R"(^([A-Za-z_]\w*)\.(first|second)\s*$)");
        std::smatch pm;
        if (std::regex_match(tp, pm, pair_mem_re)) {
          const auto pvit = var_types.find(pm[1].str());
          if (pvit != var_types.end() && pvit->second.rfind("dpp_pair_", 0) == 0) {
            // Extract type from struct name: dpp_pair_T1_T2 → T1 or T2
            const std::string ptype = pvit->second.substr(9); // strip "dpp_pair_"
            const auto under = ptype.find('_');
            const std::string field_type = (pm[2].str() == "first" || under == std::string::npos)
                ? (under != std::string::npos ? ptype.substr(0, under) : ptype)
                : ptype.substr(under + 1);
            if (field_type == "int") return "%d";
            if (field_type == "dbl") return "%g";
            if (field_type == "long") return "%ld";
          }
        }
        // Don't propagate an inner variable's type when the part is a function call —
        // the return type of the function dominates, not the type of an argument.
        static const std::regex fn_call_pat(R"(^[A-Za-z_]\w*\s*\()");
        if (std::regex_search(tp, fn_call_pat)) return "";
        // Scan for any known variable type in the expression (e.g., i+1 where i is size_t)
        static const std::regex ident_re(R"(\b([A-Za-z_]\w*)\b)");
        for (std::sregex_iterator sit(tp.begin(), tp.end(), ident_re), end; sit != end; ++sit) {
          const auto vit = var_types.find((*sit)[1].str());
          if (vit != var_types.end()) {
            const std::string spec = format_spec_for_type(vit->second);
            if (!spec.empty()) return spec;
          }
        }
        return "";
      }();
      // Check if part is a call to a dpp_string-returning function
      static const std::regex fn_call_re(R"(^([A-Za-z_]\w*)\s*\()");
      if (fs.empty() && !str_ret_fns.empty()) {
        std::smatch fcm;
        if (std::regex_search(part, fcm, fn_call_re) &&
            str_ret_fns.count(fcm[1].str())) {
          format += "%s";
          args.push_back("dpp_string_tmp_cstr(" + part + ")");
          continue;
        }
      }
      // Look up the function's known return type for format spec.
      if (fs.empty() && !fn_ret_types.empty()) {
        std::smatch fcm;
        if (std::regex_search(part, fcm, fn_call_re)) {
          const auto frit = fn_ret_types.find(fcm[1].str());
          if (frit != fn_ret_types.end()) {
            const std::string spec = format_spec_for_type(frit->second);
            if (!spec.empty()) {
              format += spec;
              args.push_back(part);
              continue;
            }
          }
        }
      }
      format += fs.empty() ? "%d" : fs;
      args.push_back(part);
    }
  }

  std::ostringstream lowered;
  lowered << indent;
  if (!label_prefix.empty()) lowered << label_prefix;
  if (to_stderr) {
    lowered << "fprintf(stderr, \"" << format << "\"";
  } else {
    lowered << "printf(\"" << format << "\"";
  }
  for (const std::string &arg : args) {
    lowered << ", " << arg;
  }
  lowered << ");";
  if (had_break) lowered << " break;";
  return lowered.str();
}

} // namespace

IostreamResult lower_iostreams(const std::string &source) {
  IostreamResult result;
  std::istringstream in(source);
  std::ostringstream out;
  std::string line;

  // Pre-scan for dpp_string-returning function declarations.
  std::set<std::string> dpp_string_fns;
  // Pre-scan for known return types of functions (for format spec resolution).
  std::map<std::string, std::string> fn_return_types;
  {
    static const std::regex dpp_str_fn_re(
        R"((?:static\s+inline\s+)?(?:dpp_string|(?:std::)?string)\s+([A-Za-z_]\w*)\s*\()");
    // Match: ReturnType fn_name(  at non-indented (global scope function definitions).
    static const std::regex fn_ret_re(
        R"(^(double|float|long|unsigned(?:\s+int)?|int|char|size_t|const\s+char\s*\*)\s+([A-Za-z_]\w*)\s*\()");
    std::istringstream pre(source);
    std::string pline;
    while (std::getline(pre, pline)) {
      std::sregex_iterator it(pline.begin(), pline.end(), dpp_str_fn_re), end;
      for (; it != end; ++it) dpp_string_fns.insert((*it)[1].str());
      std::smatch rm;
      if (std::regex_search(pline, rm, fn_ret_re)) {
        std::string rtype = rm[1].str();
        rtype = std::regex_replace(rtype, std::regex(R"(\s+)"), " ");
        fn_return_types[rm[2].str()] = trim(rtype);
      }
    }
  }

  // Track declared variable types so cout can pick the right format specifier.
  std::map<std::string, std::string> var_types;
  // Matches: double y = ...; / const double PI = ...; / char c = ...; / const char * s = ...;
  static const std::regex var_decl_re(
      R"(^\s*(?:const\s+)?(double|float|char|long|unsigned(?:\s+int)?|const\s+char\s*\*|std::size_t|size_t)\s+([A-Za-z_]\w*)\s*[=;])");
  // Also detect for-loop variables: for (size_t i = ...
  static const std::regex for_var_re(
      R"(for\s*\(\s*(double|float|char|long|unsigned(?:\s+int)?|size_t|int)\s+([A-Za-z_]\w*)\s*=)");

  while (std::getline(in, line)) {
    const std::string stripped = trim(line);
    if (stripped == "#include <iostream>" || stripped == "using namespace std;") {
      result.used_stdio = true;
      continue;
    }
    std::smatch dm;
    if (std::regex_search(line, dm, var_decl_re)) {
      std::string ctype = dm[1].str();
      ctype = std::regex_replace(ctype, std::regex(R"(\s+)"), " ");
      var_types[dm[2].str()] = ctype;
    }
    // Pick up dpp_opt_T and dpp_pair_T_U variable declarations for member access inference.
    {
      static const std::regex dpp_type_decl_re(
          R"(^\s*(dpp_(?:opt|pair)_[A-Za-z_]\w*)\s+([A-Za-z_]\w*)\s*[=;])");
      std::smatch tdm;
      if (std::regex_search(line, tdm, dpp_type_decl_re)) {
        var_types[tdm[2].str()] = tdm[1].str();
      }
    }
    // Also pick up function parameters of known types (for method signatures)
    static const std::regex param_re(
        R"(\b(double|float|long|unsigned(?:\s+int)?|const\s+char\s*\*\s*|const\s+(?:std::)?string\s*[&*]?\s*|size_t)\s*([A-Za-z_]\w*)\s*[,)])");
    for (std::sregex_iterator it(line.begin(), line.end(), param_re), end; it != end; ++it) {
      std::string ctype = (*it)[1].str();
      ctype = std::regex_replace(ctype, std::regex(R"(\s+)"), " ");
      ctype = trim(ctype);
      // Normalize const std::string / const string params to const char * for format spec.
      if (ctype.find("string") != std::string::npos) ctype = "const char *";
      var_types[(*it)[2].str()] = ctype;
    }
    // Pick up for-loop index variables: for (size_t i = ...
    {
      std::smatch fm;
      if (std::regex_search(line, fm, for_var_re)) {
        var_types[fm[2].str()] = fm[1].str();
      }
    }
    out << lower_cout_line(line, result.used_stdio, var_types, dpp_string_fns, fn_return_types) << '\n';
  }

  result.source = out.str();
  return result;
}

} // namespace dpp::convert
