#include "dpp/transpiler.h"

#include "dpp/convert/basic.h"
#include "dpp/convert/iostream.h"
#include "dpp/parser/parser.h"
#include "dpp/parser/syntax_checker.h"

#include <stdexcept>

namespace dpp {

std::string transpile_bootstrap_subset(const std::string &source) {
  const parser::ParsedSource parsed = parser::parse_translation_unit(source);
  const std::vector<parser::Diagnostic> diagnostics = parser::check_bootstrap_syntax(parsed);
  if (parser::has_errors(diagnostics)) {
    throw std::runtime_error("syntax check failed");
  }

  convert::IostreamResult iostream = convert::lower_iostreams(parsed.text);
  std::string out = iostream.source;
  out = convert::lower_structs(out);
  out = convert::lower_main_signature(out);
  out = convert::lower_aggregate_initializers(out);

  const std::string includes = iostream.used_stdio ? "#include <stdio.h>\n\n" : "";

  return "/* Generated by DummyCpp/dpp bootstrap transpiler. */\n"
         "/* Supported input is intentionally tiny; see docs/plan.md. */\n\n" +
         includes + out;
}

} // namespace dpp

