#include "dpp/transpiler.h"

#include "dpp/convert/algorithm.h"
#include "dpp/convert/assertions.h"
#include "dpp/convert/basic.h"
#include "dpp/convert/free_functions.h"
#include "dpp/convert/iostream.h"
#include "dpp/convert/map.h"
#include "dpp/convert/memory.h"
#include "dpp/convert/records.h"
#include "dpp/convert/string.h"
#include "dpp/convert/templates.h"
#include "dpp/convert/vector.h"
#include "dpp/parser/parser.h"
#include "dpp/parser/syntax_checker.h"

#include <regex>
#include <stdexcept>
#include <sstream>

namespace dpp {

std::string transpile_bootstrap_subset(const std::string &source) {
  const parser::ParsedSource parsed = parser::parse_translation_unit(source);
  const std::vector<parser::Diagnostic> diagnostics = parser::check_bootstrap_syntax(parsed);
  if (parser::has_errors(diagnostics)) {
    std::ostringstream message;
    message << "syntax check failed";
    for (const parser::Diagnostic &diagnostic : diagnostics) {
      if (diagnostic.level == parser::DiagnosticLevel::error) {
        message << "\n  error: " << diagnostic.message;
      }
    }
    throw std::runtime_error(message.str());
  }

  std::string out = convert::lower_function_templates(parsed).source;
  out = convert::lower_default_args(out);
  out = convert::lower_pairs(out);
  out = convert::lower_optionals(out);
  out = convert::lower_enums(out);
  out = convert::lower_auto_types(out);
  const convert::RecordsResult records_result = convert::lower_records(out);
  out = records_result.source;
  out = convert::lower_record_lifetime(out, records_result.destructible_types);
  out = convert::lower_free_functions(out).source;
  convert::VectorResult vector = convert::lower_vectors(out);
  out = vector.source;
  convert::MapResult map = convert::lower_maps(out);
  out = map.source;
  convert::AlgorithmResult algorithm = convert::lower_algorithms(out);
  out = algorithm.source;
  convert::MemoryResult memory = convert::lower_memory(out);
  out = memory.source;
  convert::StringResult string = convert::lower_strings(out);
  out = string.source;
  convert::IostreamResult iostream = convert::lower_iostreams(out);
  out = iostream.source;
  convert::AssertionsResult assertions = convert::lower_assertions(out);
  out = assertions.source;
  out = convert::lower_structs(out);
  out = convert::lower_main_signature(out);
  out = convert::lower_aggregate_initializers(out);
  out = convert::lower_cpp_surface_types(out);

  const std::string includes = iostream.used_stdio ? "#include <stdio.h>\n#include <stdlib.h>\n\n" : "";
  const std::string bool_include =
      std::regex_search(out, std::regex(R"(\bbool\b)")) ? "#include <stdbool.h>\n" : "";
  const std::string assert_include = assertions.used_assert ? "#include <assert.h>\n" : "";
  const std::string vector_include = vector.used_vector ? "#include \"dpp_vector.h\"\n" : "";
  const std::string map_include = map.used_map ? "#include \"dpp_map.h\"\n" : "";
  const std::string algorithm_include =
      algorithm.used_algorithm ? "#include \"dpp_algorithm.h\"\n" : "";
  const std::string memory_include = memory.used_memory ? "#include \"dpp_memory.h\"\n" : "";
  const std::string string_include = string.used_string ? "#include \"dpp_string.h\"\n" : "";

  const bool has_extra_includes =
      !bool_include.empty() || !vector_include.empty() || !map_include.empty() ||
      !algorithm_include.empty() || !memory_include.empty() || !string_include.empty() ||
      !assert_include.empty();

  return "/* Generated by DummyCpp/dpp bootstrap transpiler. */\n"
         "/* Supported input is intentionally tiny; see docs/plan.md. */\n\n" +
         includes + bool_include + assert_include + vector_include + map_include +
         algorithm_include + memory_include + string_include +
         (has_extra_includes ? "\n" : "") +
         out;
}

} // namespace dpp
