#include "dpp/transpiler.h"

#include "dpp/convert/basic.h"
#include "dpp/convert/iostream.h"
#include "dpp/convert/records.h"
#include "dpp/convert/vector.h"
#include "dpp/parser/parser.h"
#include "dpp/parser/syntax_checker.h"

#include <stdexcept>
#include <sstream>

namespace dpp {

std::string transpile_bootstrap_subset(const std::string &source) {
  const parser::ParsedSource parsed = parser::parse_translation_unit(source);
  const std::vector<parser::Diagnostic> diagnostics = parser::check_bootstrap_syntax(parsed);
  if (parser::has_errors(diagnostics)) {
    std::ostringstream message;
    message << "syntax check failed";
    for (const parser::Diagnostic &diagnostic : diagnostics) {
      if (diagnostic.level == parser::DiagnosticLevel::error) {
        message << "\n  error: " << diagnostic.message;
      }
    }
    throw std::runtime_error(message.str());
  }

  std::string out = convert::lower_records(parsed.text).source;
  convert::VectorResult vector = convert::lower_vectors(out);
  out = vector.source;
  convert::IostreamResult iostream = convert::lower_iostreams(out);
  out = iostream.source;
  out = convert::lower_structs(out);
  out = convert::lower_main_signature(out);
  out = convert::lower_aggregate_initializers(out);

  const std::string includes = iostream.used_stdio ? "#include <stdio.h>\n\n" : "";
  const std::string vector_include = vector.used_vector ? "#include \"dpp_vector.h\"\n" : "";

  return "/* Generated by DummyCpp/dpp bootstrap transpiler. */\n"
         "/* Supported input is intentionally tiny; see docs/plan.md. */\n\n" +
         includes + vector_include + (vector_include.empty() ? "" : "\n") + out;
}

} // namespace dpp
